### ISSUE TITLE
new check: no users in nonexistent zone

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#100]

**Comment by ganning127** [comment]
I'm thinking of approaching this like so:
1. Use genquery and run `iquest "SELECT order(ZONE_NAME)"` to get all valid zones
2. Use `iquest "SELECT order(USER_NAME), USER_ZONE WHERE USER_TYPE != 'rodsgroup'"` to get a list of users with their respective zones
3. Check and find (if any) zones from (2) are not present in (1)

Would be using the `/query` endpoint to access the iRODS General Query language

**Comment by trel** [comment]
1) should have a full zone report already available to ZMT, cached somewhere, so that should have the zones maybe... already?

2) a zone with 50000 users... could present a wrinkle.

3) yes.

wondering if there is a query that can do it in 'one'.

**Comment by ganning127** [comment]
I was trying to construct a query that can select all users with `USER_ZONE` not in the `ZONE_NAME` column. I came up with the following query (with the nested `SELECT`): `SELECT order(USER_NAME), USER_ZONE WHERE USER_TYPE != 'rodsgroup' AND USER_ZONE NOT IN (SELECT ZONE_NAME)`.

However, after running this, I get the message: `ERROR: iquest Error: queryAndShowStrCond failed status = -816000 CAT_INVALID_ARGUMENT`

I was thinking of declaring a variable using `DECLARE`, but it doesn't seem to work either in genquery.

If this is the case, would it be best to go with the two `SELECTS` and do the comparison on the frontend to figure out the invalid zones?

**Comment by trel** [comment]
I think we might have to do two queries and compare in the app/frontend until we have GenQuery2 available.

/cc @korydraughn

**Comment by korydraughn** [comment]
GenQuery does not support sub-selects. It may support `IN`, but not `NOT IN`.

I believe `IN` uses the syntax you expect, but without parentheses.

For now, your only option with GenQuery is probably to test each zone individually.

Another option is to define a Specific Query.

**Comment by trel** [comment]
And a Specific Query requires the admin to 'install' that query in the iRODS catalog... so makes ZMT less 'portable'.

Also/Or... could try to use a named Specific Query, and if not defined, fall back to the 'inefficient' method.

**Comment by trel** [comment]
look at `iadmin asq`

**Comment by trel** [comment]
Check the specific query of interest first, and if it doesn't exist / fails... then try the inefficient / generic way.    Consider perhaps how to give a hint to the admin about adding the specific query if they want better performance.

**Comment by ganning127** [comment]
PR Merged, closing as completed
