### ISSUE TITLE
define and validate the checkfiles

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#105]
For easier validation and communication to other administrators, define the JSON Schema for a ZMT Checkfile.

**Comment by trel** [comment]
can use https://www.jsonschemavalidator.net/ as a sandbox...

initial candidate schema
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "name": {"type": "string", "minLength": 1},
        "description": {"type": "string"},
        "minimum_server_version": {"type": "string"},
        "maximum_server_version": {"type": "string"},
        "interval_in_seconds": {"type": "integer", "minimum": 1},
        "active": {"type": "boolean"},
        "checker": {"type": "string"}
    },
    "required": [
        "name",
        "description",
        "interval_in_seconds",
        "active",
        "checker",
    ]
}
```

with `default_checkfile.json` that validates...
```
{
    name: "default_checkfile",
    description: "",
    minimum_server_version: "", // optional
    maximum_server_version: "", // optional
    interval_in_seconds: 300, 
    active: true,
    checker: "function () {
        // default result object
        let result = {
            status: 'ok',
            message: '',
            success: 0, // optional
            failed: [] // optional
        }
        // your code here

        // return
        return result
    }"
}
```

two things...

1) not sure about defining the 'checker' as a string... might need some more tweaking there...   'string' seems best...
   https://json-schema.org/understanding-json-schema/reference/type.html

2) the checkfile itself is currently implemented as a `.js` object, but I think it should be considered a payload, just `.json` itself and loaded into a variable... and then the application can just walk these and add them to a list?   The application should complain if the names are not all unique among all checkfiles.

**Comment by ganning127** [comment]
Just want to make sure that I understand this correctly. Currently, the checkfiles are written in JavaScript. Is this issue saying the following?

1. All the current `.js` checkfiles should be re-written to be in JSON format, and have a loader for the overall checks load all these JSON files and run the checks within them.
2. The format (required keys, etc) of each JSON checkfile should be in the schema you proposed above

**Comment by trel** [comment]
Yes - both of those are the ideas, if I remember correctly.   Not convinced either/both are correct.

The upside of having a schema is that we can validate new ones / candidates / handcrafted additions... and catch errors early.   The downside is we might be making the syntax too hard to be easy to hold / use.

Bonus points if you can solve for both power/validation AND ease of use and reading.

**Comment by ganning127** [comment]
Hmm, I don't think that doing the checkfiles as JSON is a great idea:
1. You can't import libraries like `axios` into `.json` files, meaning for checks that need to call the cpp rest API, we won't be able to do that as easily anymore, and all existing checkfiles that use axios need to be modified to not use any external libraries.
2. Having the checker function as a string means no syntax highlighting and would make development more difficult. You also [can't easily store functions in JSON](https://stackoverflow.com/questions/36517173/how-to-store-a-javascript-function-in-json).
3. You can't have comments in JSON, making documentation more difficult
4. the format we are using is structured very similarly to JSON but with all the extra features, like imports.

Not sure that JSON Schema Validator can take the format that we're using though

**Comment by trel** [comment]
These are all valid concerns and reasons not to touch what is already working.

So... how can we validate these checkfiles?  A subset?  Programmatically?

If we determine we cannot, then that's okay, but it should be an informed decision - and we'll have to do a solid job in documentation rather than in a validator.

**Comment by korydraughn** [comment]
Perhaps having a real server would help with this.

The checkfiles could be moved to the server and then you get more options to use whatever you like.

For example, if the backend server is written in python/flask, then you can define a base class for checkfiles and all required methods of the class throw exceptions until the admin overrides the behavior.

I sense we want to introduce a server for this at some point. For now, it could simply be responsible for checkfiles.

**Comment by ganning127** [comment]
If I'm not mistaken, we already have a "built in" version of checkfile validation on ZMT in `CheckContext.js`:

```
const validateChecks = (checks) => {
    return checks.reduce((acc, curr) => {
        if (!curr.name || !curr.description || !curr.interval_in_seconds || curr.interval_in_seconds < 0 || !curr.checker || (curr.minimum_server_version && curr.maximum_server_version && irodsVersionComparator(curr.maximum_server_version,curr.minimum_server_version) < 0)) {
            curr.isValid = false
            curr.active = false
        }
        else curr.isValid = true
        acc.push(curr)
        return acc
    }, [])
}
```


This function checks each property and makes sure that it is valid. If it is invalid, then it says so:

<img width="762" alt="Screenshot 2023-06-22 at 12 24 27 PM" src="https://github.com/irods/irods_client_zone_management_tool/assets/62436772/eaa18906-0695-4758-b0e1-a09aca871457">

**Comment by ganning127** [comment]
Would something like this work? We can certainly add more strict rules, like about the length of a property as well.

**Comment by korydraughn** [comment]
Oh. That does look like a validator.

I guess I don't quite understand the reason for JSON schema here.

**Comment by trel** [comment]
This can certainly be tightened up a little, but yes, maybe our needs are already met.   Not sure when this issue was made compared to that validateChecks function.    Happy to move forward without JSON schema if this is doing the job.

**Comment by ganning127** [comment]
Yep, I think `validateChecks` is doing the basics of validation. Are there any more rules that we want to add to this? Looking at the JSON schema you had above, we could add
- make sure that `name` and `interval_in_seconds` have a min length of 1
- `name`, `description`, `minimum_server_version`, `maximum_server_version`, `interval_in_seconds` are strings
- `active` is boolean

**Comment by trel** [comment]
seems good - yes, please add rules that seem good/true.

**Comment by ganning127** [comment]
PR merged. Closing as completed
