### ISSUE TITLE
new check: are any unixfilesystem resources about to run out of space

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#109]

**Comment by ganning127** [comment]
There is a column in genquery called `RESC_FREE_SPACE` that we can use to check for how much free space is left in that resource. What is the minimum amount of free space that should be reasonable before this check fails?

**Comment by trel** [comment]
There's not a good default for everyone... Some installations commonly move files around that are tens of gigabytes, so 2-3 of those is 'too late' to be helpful for a check... but other installations would never fill up 50GB... so...

Let's go with 10GB as a starting point for now - getting that close to filling up should definitely set off alarm bells for everyone.

**Comment by ganning127** [comment]
Gotcha, will work on doing 10 GB for now. Just realized that the `RESC_FREE_SPACE` column does not have any values for any of my resources (do they have a default max space allowed?). 

<img width="659" alt="Screenshot 2023-06-18 at 10 52 57 PM" src="https://github.com/irods/irods_client_zone_management_tool/assets/62436772/53d576ac-b91e-4b1d-b5e5-3e16684cb3da">

Looking at `iadmin`, there's `modresc`, which allowed me to set the free space on a resource. Though, it seems like I can input anything for that, including like the string `asdfasdf` and it still is set. I'm not really sure how to access free space on the resource and what units they are supposed to be in.

**Comment by trel** [comment]
It's just a string value, so ZMT would need to accommodate the possibilities.

https://docs.irods.org/4.3.0/plugins/composable_resources/#unixfilesystem

If it exists, and if it converts cleanly to an integer, and it's smaller than the value we compare against... then we'll define this check to be in violation.  Otherwise, it's not.   Or ... maybe we set it to 'yellow' because the admin could be getting better information from the system if it *was* set to a value.

**Comment by ganning127** [comment]
Sounds good. The docs you sent has the examples in bytes, so I'll do some conversions when parsing the string value from `RESC_FREE_SPACE` to convert that to check against 10 GB. 

Also, I like the idea of having the health check result set to yellow if the parse fails / none exists. If it's less than 10 GB we'll show a red.

**Comment by trel** [comment]
right, we only ever compare in bytes and seconds around here.   everything else introduces fuzziness.

**Comment by trel** [comment]
a UI can show other things, but underlying the math is the common base unit.

**Comment by ganning127** [comment]
PR merged, closing as completed.
