### ISSUE TITLE
distinguish between catalog service providers and consumers

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#11]
certainly in naming... but also perhaps in color...

possibly another color to be defined for #7

**Comment by trel** [comment]
related to #10

**Comment by connectbo** [comment]
Do we have any existing color preferences for catalog service providers and consumers?  If not, I can draft some possible solutions. Also I can preset some profiles for color/naming and users can specify which in the .env file, insteading of providing name/hex color by themselves?

**Comment by trel** [comment]
some defaults are good and should be in the config.

- provider - slight irods green hue
- consumer - just a grey

just want people to be able to match their company if that's important to them.

**Comment by trel** [comment]
they won't need to provide names, just colors.   we'll call them what we call them :)
