### ISSUE TITLE
new check: using coordinating as leaf

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#110]
are any replication, random, passthru resources currently leaf resources in existing hierarchies

**Comment by trel** [comment]
similar to #111

**Comment by ganning127** [comment]
Is this issue just saying that if replication, random, passthru resources have any children, then the check fails?

**Comment by trel** [comment]
No, not quite... resources of those types listed above... should not be last / leaf ... aka, they should ALWAYS have at least one child.

**Comment by ganning127** [comment]
Shoot yet, I forgot to type the "don't" before "have" lol. But isn't what you're saying about how these coordinating resources should always have one child already in https://github.com/irods/irods_client_zone_management_tool/pull/162?

**Comment by trel** [comment]
ah, yes - you can point that coordinating commit / work to this issue.
