### ISSUE TITLE
new check: storage resources with children

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#111]
do any storage resources (unixfilesystem, univmss, s3) have children, if so, fail.

**Comment by ganning127** [comment]
A few questions about this:
1. If a resource has children, does that mean it fails/passes this check?
2. The genquery columns have a `RESC_CHILDREN` property. However, it seems like even for resources with children, that column is blank. See the screenshot below. However, the `RESC_PARENT` column does is populated on child resources. Thus, we can create a set of all parent resources and those will be the resource IDs with children.

<img width="685" alt="Screenshot 2023-06-16 at 10 44 20 AM" src="https://github.com/irods/irods_client_zone_management_tool/assets/62436772/2eadd66d-03fb-4088-921a-5b81577d113b">

**Comment by trel** [comment]
Yes, storage resources are 'always' the leaves.   At least until we think of a counterexample.

aka, a unixfilesystem should never have a child.

Coordinating resources (not the leaves) (passthru, replication, etc.) can/should have children.

**Comment by trel** [comment]
Yes, `RESC_PARENT` is the thing to key on here - a node can only have one parent.

`RESC_CHILDREN` is a legacy/vestigial column - we do not use it anymore.

**Comment by ganning127** [comment]
Got it, so the checks I'll implement will be:
- if a unixfilesystem has children (AKA is in the parent resources set), fail check
- if a passthru, replication, Load Balanced, compound, Random, Deferred resource has no children (AKA is not in the parent resources set), fail check 

Does this sound right?

**Comment by trel** [comment]
any storage resource: unixfilesystem, s3, univmss

i think coordinating resources without children could be a separate / distinct checkfile.    or maybe even separate checkfiles for each type (since passthru is defined to have one-and-only-one child) (random should have more than 0).

**Comment by trel** [comment]
yes, one checkfile for storage, one for coordinating (for now).
