### ISSUE TITLE
new check: resources with problematic characters

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#112]
resources with names with spaces, or other potentially problematic characters

**Comment by ganning127** [comment]
Seems like the rules regarding resource names are:
```
    // Must be between 1 and NAME_LEN-1 characters.
    // Must start and end with a word character.
    // May contain non consecutive dashes.
``` 
(from [db_plugin.cpp](https://github.com/irods/irods/blob/1c360003aea23c9bb80025c3c62dc7a0cef29524/plugins/database/src/db_plugin.cpp#LL684C23-L684C49))

Word characters are a-z, A-Z, 0-9, and includes underscore

**Comment by ganning127** [comment]
I'm thinking about just including a check that uses that exact regex to match resource names on the health cehck

**Comment by trel** [comment]
That seems fine - and please leave a hint/comment in the code for later researchers to know 'why' and 'from where'.

**Comment by trel** [comment]
@ganning127 I think you may have a close button now...

**Comment by ganning127** [comment]
i do, hooray!
