### ISSUE TITLE
new check: resources with names that are too long

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#113]
defined to be... 63(?) characters?    need to confirm.

**Comment by ganning127** [comment]
Isn't this already done?

**Comment by korydraughn** [comment]
The issue is asking whether 63 is the correct value.

You're going to have to look at the database schema and the APIs handling resource names.

The cpp source files in question are:
- rsGeneralAdmin.cpp
- db_plugin.cpp

It is possible that the API isn't aligned with the database schema. We need to investigate that before this question can be answered.

**Comment by ganning127** [comment]
Just leaving these here for future reference:

`rsGeneralAdmin.cpp`: https://github.com/irods/irods/blob/1c360003aea23c9bb80025c3c62dc7a0cef29524/server/api/src/rsGeneralAdmin.cpp

`db_plugin.cpp`: https://github.com/irods/irods/blob/1c360003aea23c9bb80025c3c62dc7a0cef29524/plugins/database/src/db_plugin.cpp

**Comment by ganning127** [comment]
I believe that 63 characters is correct:

- Looking at `db_plugin.cpp`: [this line's regex](https://github.com/irods/irods/blob/1c360003aea23c9bb80025c3c62dc7a0cef29524/plugins/database/src/db_plugin.cpp#LL684C23-L684C49) (`^(?=.{1,63}$)\\w+(-\\w+)*$`) validates that the length needs to be between 1 and 63 characters long

- Looking at `rsGeneralAdmin.cpp`: [this line](https://github.com/irods/irods/blob/1c360003aea23c9bb80025c3c62dc7a0cef29524/server/api/src/rsGeneralAdmin.cpp#LL367C1-L368C1) `std::strlen(_resource_name) >= NAME_LEN;` suggests that `NAME_LEN` is the max resource length name, but there's also a variable called `MAX_NAME_LEN` that could also be it. Still looking around the header files as to what `NAME_LEN` is defined to be 

However, `db_plugin` needs a resource name that's between 1 and 63 characters, while the checkfile in ZMT only checks for less than 63, so it may be worth also adding a check for >= 1 character long.

**Comment by trel** [comment]
NAME_LEN is 64

https://github.com/irods/irods/blob/1c360003aea23c9bb80025c3c62dc7a0cef29524/lib/core/include/irods/rodsDef.h#L39

**Comment by ganning127** [comment]
Since `NAME_LEN` is 64, `rsGeneralAdmin.cpp` suggests that any names with chars >= 64 will throw an error, meaning that 63 is the maximum length.

Both files agree that 63 characters is the max length for a resource name.

**Comment by trel** [comment]
Good.  I agree.

So... this issue can be closed with no action needed?   One more vote and we can close it.

**Comment by korydraughn** [comment]
I think this can be closed.
