### ISSUE TITLE
manage zones

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#128]
- need new left sidebar entry / page to manage zones
   - cannot edit the current local zone, but can add/remove/edit 'remote' zones
   - each zone has a hostname and port, stored in the catalog as 'connection'
   - each zone has a comment too
   - from zone_report or directly...`iquest "select ZONE_NAME, ZONE_CONNECTION, ZONE_COMMENT where ZONE_TYPE = 'remote'"`
- new user creation needs a drop down with all available zones, default selected to the local zone

**Comment by connectbo** [comment]
got it.
