### ISSUE TITLE
REST calls will not work with 0.9.2

### ISSUE THREAD

**Issue by alanking** [irods/irods_client_zone_management_tool#142]
Several changes have occurred in the run up to 0.9.2 in the REST C++ client. The REST calls used in this client need to be updated to reflect the new endpoints and options.

**Comment by alanking** [comment]
Not sure.

Have we tried to maintain backward compatibility in the past as new endpoints were added/changed? If we do this, then it will only mean that upgrading ZMT does not also require upgrading the REST client deployment with which it is communicating.

I am personally of the opinion that we should forge ahead and just tie future releases together until 1.0.0 for one or the other, or both. Thoughts?

**Comment by trel** [comment]
sounds good to me - burn it down!

**Comment by alanking** [comment]
Confirmed that existing REST operations are behaving with 0.9.2 C++ REST client release. We can open new issues if they arise
