### ISSUE TITLE
new check: passthru resources should have exactly one child

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#148]
similar logic as
https://github.com/irods/irods_client_zone_management_tool/blob/main/src/data/checkfiles/default_checkfiles/compound-resc-children.js

**Comment by ganning127** [comment]
I'll start tackling this soon. This check will be sort of similar to https://github.com/irods/irods_client_zone_management_tool/pull/162. Should I add this to the coordinating resource checkfile (which may get messy), or include it was a whole new checkfile (which should be cleaner/easier to understand)

**Comment by trel** [comment]
this is separate because of the strict count of 1 child being required.
