### ISSUE TITLE
Filtering on `/users` should search all columns, not only by user name

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_zone_management_tool#153]
Right now this filter box only acts on "User Name" ![image](https://github.com/irods/irods_client_zone_management_tool/assets/62436772/20893b94-636b-4530-9da9-bbcd7fde05d6)

**Comment by trel** [comment]
You're saying that it should search by zone name and zone type as well?

**Comment by ganning127** [comment]
Yep, that's what I was thinking

**Comment by trel** [comment]
seems reasonable to try it out.    let's think through how it could be confounding/confusing/notbetter as well.

**Comment by ganning127** [comment]
Sounds great, I'll get started on implementing this soon. It may be confusing when the user name is similar to the zone name, and then the user won't know how the filtering is actually happening.

Alternatively, we can also have dropdowns for the other columns like zone and user type, and keep the search field only searching for user name.

**Comment by ganning127** [comment]
closing as completed, PR merged.
