### ISSUE TITLE
Change browser tab title based on which page in ZMT the user is on

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_zone_management_tool#155]
For example, if the user is on the "Tickets" page, the tab title would be "Tickets - iRODS Zone Management Tool"

**Comment by trel** [comment]
Oh... we don't do that?

Consider flipping it - "iRODS Zone Management Tool - Tickets" ?     Or is that not as helpful when scanning the titles in some other listing...

**Comment by ganning127** [comment]
It doesn't do that right now. I think it's up to personal preference on which order, but I like "Tickets - iRODS Zone Management Tool" better because it's easier to scan for when you have a lot of tabs open and can only see the first few letters of the tab title.

You can also see that it's the ZMT based on the favicon.

**Comment by trel** [comment]
Hopefully we can set this type of thing in a single place for all pages / entire app?

So if we change our minds later, we can just switch the order?

**Comment by ganning127** [comment]
Yep, we can definitely do that. In the `.env` file, we can define something like:

```
REACT_APP_USERSE_TITLE=Users | iRODS Zone Management Tool
REACT_APP_TICKETS_TITLE=Tickets | iRODS Zone Management Tool
...
``` 

And we can take that information and spread it to each site title.

**Comment by trel** [comment]
interesting.   that creates multiple points of truth perhaps... 

consider maybe a single setting that is "$page - $app" or "$app - $page"... basically to create a little token system where someone can swap or redefine the title... for all pages of the app.    can discuss.

**Comment by ganning127** [comment]
Sure, we can definitely do that. Though that would mean in each page, we would nee to do a short little if-statement to determine if its page - app or app - page.

Something like:

```
document.title = environment.appOrder == 'first' ? 'iRODS ZMT - {ticketsTitle}' : '{ticketsTitle} - iRODS ZMT';
```

**Comment by trel** [comment]
or the setting itself tells you what to do - and then the app just decodes and prints...  a little DSL with two tokens.

**Comment by ganning127** [comment]
Just played around with this. We can add a new property in `EnvironmentContext.js` called `titleFormat`: 
```
        <EnvironmentContext.Provider value={{
            deviceType: deviceType,
            restApiLocation: process.env.REACT_APP_REST_API_URL,
            restApiTimeout: process.env.REACT_APP_REST_API_CONNECTION_TIMEOUT_SECOND,
            primaryColor: process.env.REACT_APP_PRIMARY_COLOR,
            appbarLogo: process.env.REACT_APP_APPBAR_LOGO,
            loginLogo: process.env.REACT_APP_LOGIN_LOGO,
            brandingName: process.env.REACT_APP_BRANDING_NAME,
            pageTitle: "",
            titleFormat: function () {
                return `${this.pageTitle} - ${this.brandingName}`
            }
        }}>
            {children}
        </EnvironmentContext.Provider>
````

And then in `User.js`, we can use:
```
        environment.pageTitle = "Users"
        document.title = `${environment.titleFormat()}
```

**Comment by trel** [comment]
please close if this is complete.
