### ISSUE TITLE
inactive checks can still run

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_zone_management_tool#166]
<img width="1293" alt="Screenshot 2023-06-23 at 3 07 28 PM" src="https://github.com/irods/irods_client_zone_management_tool/assets/62436772/425ed5c0-486e-44da-a841-efa2bd94d20f">

I think we just need to add (`&& check.active`) to line 141 in `CheckContext.js`

**Comment by trel** [comment]
hmm, pretty sure this is a regression if true.   good catch.

**Comment by ganning127** [comment]
Seems like to me it's still happening:
<img width="1850" alt="Screenshot 2023-06-26 at 9 54 28 AM" src="https://github.com/irods/irods_client_zone_management_tool/assets/62436772/b9e88235-cecd-48b4-b931-5473646bfcbb">

**Comment by ganning127** [comment]
PR Merged. Closing as completed.
