### ISSUE TITLE
Add query string parameters to `/specific-query` called `add` and `alias` that allows you to pre-populate adding specific query

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_zone_management_tool#169]
Something like this:

<img width="1683" alt="Screenshot 2023-06-28 at 10 08 34 AM" src="https://github.com/irods/irods_client_zone_management_tool/assets/62436772/77aef6d5-a280-472d-bf32-9fcd5b213857">

**Comment by ganning127** [comment]
Could have the unused metadata checkfile and users with no zone prs use this

**Comment by trel** [comment]
looks nice.

please make sure the query string parameters are url-encoded(?)... shenanigans can happen up there if not.

**Comment by trel** [comment]
seeing an asterisk in a URL is ... jarring.

**Comment by ganning127** [comment]
Ohhh yep, great point. Will make sure that's in the eventual PR

**Comment by ganning127** [comment]
PR merged, closing as completed

**Comment by ganning127** [comment]
Need to add `encodeURIComponent` to `SpecificQueryController.js` to handle all cases of `sqlStr`
