### ISSUE TITLE
Servers page crashes when clicking on `Details`

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_zone_management_tool#175]
the key: `host_access_control_config` should instead be `server_config`

Currently lookes like this when clicking on `Details`:
<img width="1780" alt="Screenshot 2023-07-03 at 6 03 52 PM" src="https://github.com/irods/irods_client_zone_management_tool/assets/62436772/60151ffc-7d9f-497a-bd3c-d1705c35d852">

**Comment by trel** [comment]
this did not used to be broken - can we go back and find when this behavior changed?

what do you mean about the key being incorrect?

**Comment by ganning127** [comment]
Will look into when the behavior changed. I think since I spun up irods_demo to work on ZMT, this has been broken (ie 4.3.0) doesn't work with this.

Also the incorrect key is in `Server.js`: https://github.com/irods/irods_client_zone_management_tool/blob/7c53df89ce88a1a5ccb51ed692b29f0a2f03b910/src/views/Server.js#L126-L127

**Comment by ganning127** [comment]
I could be wrong, but the first mention I found of `host_access_control_config` (the problematic key) was here, and hasn't changed since.
 https://github.com/connectbo/irods_client_zone_management_tool/commit/43f78be0e5c86455ea3e70e58df9e8ac44c88ea1

**Comment by trel** [comment]
Yes, we converged that setting into the main server_config in 4.3.0.   So as soon as talking to 4.3.0, I expect this would/did not work as it used to.

**Comment by ganning127** [comment]
PR merged, closing as completed.
