### ISSUE TITLE
create variable for maximum number of servers to list

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#178]
currently hard-coded to 10...

https://github.com/irods/irods_client_zone_management_tool/blob/5fdf9ed9c095eebaa945102878f4d5588b737826/src/contexts/ServerContext.js#L457

we should pull out this value into an app-wide variable with a default of 10.

perhaps...

`REACT_APP_DISPLAY_MAXIMUM_NUMBER_OF_SERVERS=10`

**Comment by ganning127** [comment]
I interpreted the variable wrong. Going to close this PR and make a new issue for remembering default display settings.

**Comment by trel** [comment]
opened https://github.com/irods/irods_client_zone_management_tool/issues/181
