### ISSUE TITLE
add bumpers for group removal

### ISSUE THREAD

**Issue by connectbo** [irods/irods_client_zone_management_tool#18]
Have a dialog when clicking the 'remove' button. Let user double-check if that is the one to remove. Should work similar as user/resource page.

- display groupname
- be able to display error message during remove operation

**Comment by trel** [comment]
And the remove button should not even appear if there are members in the group, I think...

**Comment by connectbo** [comment]
Got it. I can limit that functionality based on the user counts. Do we need to have extra bumpers for user/resource removal as well?  RIght now, rodsadmin user aren't shown on the user page which means they don't have remove button. For resources, each has a remove button but any error message comes from rest-api remove endpoint will be shown.

**Comment by trel** [comment]
Other `rodsadmin` users can be removed, but we should definitely have an 'are you sure?' step...   It's possible there might be a good metric for not showing this button also.  We can think on that later.

Resources cannot be removed if there are data objects on them (even in the trash).
