### ISSUE TITLE
ZMT should remember the number of rows per page on /servers, /resources, /users, /groups

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_zone_management_tool#181]
default settings: 10 per  page?

ZMT will store the user's default in localStorage. The keys will be:
`zmt-servers-perpage`, `zmt-resources-perpage`, `zmt-users-perpage`, `zmt-groups-perpage`

open to discussion about default settings and the naming

**Comment by ganning127** [comment]
for reference, current keys in localStorage for ZMT are: `zmt-username` and `zmt-token`.

to solve this issue we'll need to modify the perPage state initial value with localstorage, and also ServerContext.js to utilize that initial value

**Comment by trel** [comment]
consider `zmt-perpage-resources`, `zmt-perpage-servers`, `zmt-perpage-users`, etc.    that way they sort alphabetically?   somewhere?   purely aesthetic, of course.

let's default to 25 or 50, rather than 10.

**Comment by ganning127** [comment]
PR Merged, closing as completed.
