### ISSUE TITLE
Use /info endpoint for HTTP API health check

### ISSUE THREAD

**Issue by farbs03** [irods/irods_client_zone_management_tool#186]
This endpoint can be used to check if the HTTP API is available.

**Comment by korydraughn** [comment]
Please provide a link to the source lines which this is for.

**Comment by farbs03** [comment]
I don't think this would involve modifying any existing code, it would likely involve creating a new check file somewhere in `src/data/checkfiles`

**Comment by korydraughn** [comment]
Really? How could this work without modifying the code to use `/info`?

**Comment by farbs03** [comment]
There aren't any checkfiles that exist for the info endpoint, or any checkfiles that make a call to it (to my knowledge).

**Comment by trel** [comment]
How are we currently making the little green circle at the bottom of the UI appear?  Bottom left...

**Comment by korydraughn** [comment]
This issue was created as a result of the second bullet for commit 6682e7e. Here's the bullet item of interest.
```
- Uncheck /query endpoint, as there isn't a general GET request that can be used to check if the endpoint is up; is there another way of checking this?
```

Sounds like this issue may not serve a purpose?

**Comment by trel** [comment]
Oh, I think we removed that little green dot at the bottom of the footer...

https://github.com/irods/irods_client_zone_management_tool/blob/8f4a71033c30d974bee602867e0931000ebcdf16/src/components/footer.js

Yes, I'm not sure we need this issue.  Let's let it ride until we get the other things settled...
