### ISSUE TITLE
Revisit resource fields in `src/data/checkfiles/default_checkfiles/unixfilesystem-resc-space.js`

### ISSUE THREAD

**Issue by farbs03** [irods/irods_client_zone_management_tool#187]
Some fields are blank, such as resc[6], which represents the free space available in the resource.

**Comment by korydraughn** [comment]
Please provide a link to the source lines of interest.

**Comment by korydraughn** [comment]
The source file is in the title. My bad.

**Comment by alanking** [comment]
I'm marking this as a bug, but please update label(s) as appropriate and possibly include more words so the issue is clear(er).

**Comment by trel** [comment]
I saw this behaving as expected (I think) with #184 against proto-0.4.0 of HTTP API.

So... need some proof / screenshot of it not working as designed/expected.

**Comment by korydraughn** [comment]
Ohhh, this is about the free space value for resources being empty.

Free space isn't guaranteed to be non-empty so this issue can be closed if ZMT handles it appropriately.

**Comment by trel** [comment]
Right, you have to have something in the server for it to appear in the ZMT.

We could display something like 'not set' ... but that feels... weird.

**Comment by trel** [comment]
And I demonstrated updating the freespace FROM ZMT when pointed at a local pre-0.4.0 build of HTTP API.

So... yes, I vote for close it.

**Comment by korydraughn** [comment]
Cool. Closing.
