### ISSUE TITLE
add connection status on the login page

### ISSUE THREAD

**Issue by connectbo** [irods/irods_client_zone_management_tool#19]
Have a green(OK)/red(Error) status bar will help user determine if REST Api deployment or the its url  in .env is correct.

Click on the status bar will pop up a new window showing each endpoint status(currently /auth, /zone_report, /admin, /query), along with a retry button for each.

**Comment by connectbo** [comment]
On the login page:
![image](https://user-images.githubusercontent.com/33065086/110490789-a5477f80-80be-11eb-8e9f-85bc29d6be7f.png)

When you click on the status bar: (in this case, admin endpoint is down)
![image](https://user-images.githubusercontent.com/33065086/110490872-b7292280-80be-11eb-8ce6-0adbe977495a.png)

**Comment by connectbo** [comment]
Can talk more tomorrow. In short, I refactored the footer component and implemented the connection context provider, having that will greatly decrease the rendering time.  We will have a single button to test all the endpoints, all status will go from N/A to either 'OK' or 'Error', 'loading' status will end when reach the timeout limit.

**Comment by trel** [comment]
That's very clean.   Consider 'ERROR' in all caps.

Remember not to add # to the commit messages yet - it clutters this part of the conversation before the PR is ready.
