### ISSUE TITLE
Filter function in edit page

### ISSUE THREAD

**Issue by connectbo** [irods/irods_client_zone_management_tool#24]
Current edit page does not support filtering, which means there is no way for user to find out a group or user among hundreds or thousands. Implementing dynamic filtering function in both edit-user and edit-group page will help. The filter function would also detect whether a user is in this group or not (or a group has this user), and display the functionality accordingly.

**Comment by trel** [comment]
let's change this to 'filter', rather than 'search'.

**Comment by trel** [comment]
I still see 'search' everywhere... reopening.

**Comment by connectbo** [comment]
I think #27 may cover this, fixing is on the way. I can include both issue number in commits

**Comment by trel** [comment]
ah, right.   sorry.   closing!
