### ISSUE TITLE
release activities for ZMT 0.1.0

### ISSUE THREAD

**Issue by connectbo** [irods/irods_client_zone_management_tool#45]
- [x] HTML
  - [x]  clean up comments
  - [x] have 404 and 5xx error page #47 
  - [x] any anchor tag with target="_blank" should have a rel="noopener" attribute to prevent tab nabbing
  - [x] lint check #53 
- [x] CSS
  - [x] responsive design, mobile friendly, check at different resolution width<= 768px, 1024px, etc..
  - [x] css validator, and stylelint
  - [x] test on different kernel browsers (Safari, Firefox, Chrome, Internet Explorer, EDGE...)
  - [x] test on mobile browsers
- [x] Image
  - [x] images are optimized to be rendered in the browser
  - [x] width and height are set to limit the rendering
  - [x] have alternative text when image is not available
- [x] Functionality
  - [x] Test with the latest irods client rest api
  - [x] Authentication
  - [x] User/Group Page Scenario
    - [x] Listing + Sorting
    - [x] Add new user/group (various name case) + key event
    - [x] Delete user/group
    - [x] Edit user group
  - [x] Resource Page Scenario
    - [x] Listing + Sorting
    - [x] Add new resource, handle error messages if not created successfully + key event
    - [x] Edit resource attribute, hostname, vault path, context string, comment
    - [x] Remove resource, show error message
    - [x] Treeview Drag and drop
  - [x]  Zone report Scenario
    - [x] display all zone data appropriately
- [x] Update README

**Comment by trel** [comment]
i think we can hold on Accessibility and Performance for 0.1.0.

we're aiming for full coverage of basic functionality - so others can easily see what we're doing and have some opinions before we get too deep.

rest of the list looks pretty good - some of the CSS and Image optimization stuff could be bumped too.

**Comment by trel** [comment]
Are there any release activities other than... tag the repository when ready?

Do we need to produce any artifacts/tarballs/packages?

**Comment by connectbo** [comment]
I don't think we need to produce any other artifacts. I think we have conversations about pushing zmt images to docker hub, but I remembered you said some env vars might not be able to load. Tagging the repo should be good.

**Comment by trel** [comment]
yeah, we don't know enough about that stuff yet, even if it is the 'right answer'.    okay, cool, so release activities will just be deciding it's done... and pushing a tag.

**Comment by trel** [comment]
I think we're pretty close.

We are waiting on an initial release of https://github.com/irods/irods_client_rest_cpp

**Comment by connectbo** [comment]
Cool, I have a couple of enhancement ideas in mind. Will address those later today.

**Comment by trel** [comment]
please checkbox these - i think we're really close.

**Comment by connectbo** [comment]
Done. I think that's probably it. The compound resource one, do we want to have it here as well?

**Comment by trel** [comment]
nah, we've got milestones for that - closing!
