### ISSUE TITLE
show active area of navigation

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#6]
either the navigation should show a different color for the 'page' you're on, or we introduce consistent breadcrumbs near the top of any page to show where the user is in the app.

if we don't have two-levels of navigation (which we do not at the moment)... then an active color in the sidebar is sufficient, and saves space.

**Comment by trel** [comment]
When editing a user, or group, or resource... the sidebar should stay highlighed since we're still 'in' that section.

**Comment by trel** [comment]
i've lost the 'active' highlighting when running master.    is it working for you?

**Comment by connectbo** [comment]
Let me figure this out. Should be something wrong happening in the sidebar.
