### ISSUE TITLE
add key event (return) to text field entries

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#60]
when editing a resource (for example)...  it would be nice to hit enter... and the value I typed to be 'saved'.

<img width="853" alt="Screen Shot 2021-09-01 at 4 24 56 PM" src="https://user-images.githubusercontent.com/55238/131740129-3bec9029-0d0e-44d2-80e6-43c88cdb75f0.png">

I think it should also just 'close' the text area and repaint just that resource's details..., not necessarily refresh the entire page... the refresh takes the user away from their search and the resource they were editing... maybe they wanted to edit a second field...   this can be a new issue if requires more changes (aka no modal 'success' dialog, etc.)

**Comment by connectbo** [comment]
Right. I was also thinking about if we should have just one 'edit' button and one 'save' button for a resource? So all fields can be turned into textfields and be updated by clicking 'save' or hitting 'enter' once. For now, user might have multiple textarea open and it's hard to determine which field they want to update (we could let only one textfield open at one time, but not sure that's something we want).

**Comment by trel** [comment]
This is implemented - new edit panel, very nice.    Closing!
