### ISSUE TITLE
new resource fields should be sanitized

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#61]
when creating a new resource... i was able to add some spaces or a tab character and they made it into the database... which, due to them being a hostname... made iRODS timeout in talking to all its resources during new connections.

these fields should be trimmed for all whitespace (front and back) before sending to the server.

seen in the screenshot and then in the database... `ip-172-31-13-194%20%20`

<img width="848" alt="Screen Shot 2021-09-02 at 1 06 58 PM" src="https://user-images.githubusercontent.com/55238/131887378-d1dd9d74-4c17-446a-88c8-ce2133629584.png">

also note the incorrect dialog box...
- "Vault Path" -> "Hostname"
- "Zone" should be dropped from this dialog
- "Vault Path" should be added, with correct value

**Comment by connectbo** [comment]
I see.. whitespaces are causing trouble. Will come up with a pr to address these. 

I am also wondering if we will get an error from iRODS when the hostname/vault path provided is entirely wrong (like some random string)? If not, we probably need to validate ip/vault path first?

**Comment by trel** [comment]
That’s the trouble - there’s no way to know what the admin is trying to do ahead of time.  But we know that leading/trailing whitespace  is wrong.  Everything else *could* be right...

**Comment by connectbo** [comment]
While fixing and testing this, I also notice iRODS would return an error when the new `resource name` include any whitespaces from the middle. So we may want to trim all the whitespace in resource name.

See below: 
resource name: `testRes c4`

![image](https://user-images.githubusercontent.com/33065086/131898763-f65758ee-651a-4854-815a-1a1942f8ba9b.png)

**Comment by trel** [comment]
hmmm, perhaps.    or, we trim leading/trailing whitespace.... and then, well, show them the error that they should be able to spot.   not sure we want to *change* their input... 

but maybe it's okay in this one case...   open to discussion.

**Comment by connectbo** [comment]
That's true. I tested a bit yesterday and later I felt it might be rude to _change_ their input without telling them why. It's better to give them the error code and they can figure out by themselves.

**Comment by trel** [comment]
okay - yes, let's just `trim()`.

**Comment by trel** [comment]
oops, not quite done.
