### ISSUE TITLE
too many options in the dropdown for new resource

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#63]
when creating a new resource, the dropdown should be populated with the list of available resource plugin types.   This information... is in the zone_report, I believe.

let's see what it looks like with just the lowercase names, too.

<img width="403" alt="Screen Shot 2021-09-03 at 9 35 38 AM" src="https://user-images.githubusercontent.com/55238/132013951-27db6275-429c-4364-a3f7-8c49699b7303.png">

**Comment by connectbo** [comment]
ahh, roger that. will poke around and update the dropdown.
