### ISSUE TITLE
inconsistent display of footer

### ISSUE THREAD

**Issue by connectbo** [irods/irods_client_zone_management_tool#65]
Some weird extra space between footer and main component when scrolled down to the bottom and up to the top again:

![image](https://user-images.githubusercontent.com/33065086/132404118-f67833f5-a607-49fa-9a4e-d349709b6735.png)

The footer should stay at the bottom all the time, and main component can be infinite scolling. We could also adding a 'Back to top' button?

**Comment by trel** [comment]
'back to top' could work, but definitely secondary (or later).    if ever hit accidentally, they're very annoying.

**Comment by connectbo** [comment]
yeah i just did some experiments - hard to find a perfect position for it :)
