### ISSUE TITLE
filters should be case-insensitive for ease of use

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#68]
I think it will be a better user experience if the filters are case-insensitive instead.

- users
- resources
- groups

**Comment by connectbo** [comment]
Got a question on this as well - I think the solution might be using the `uppercase` keyword before the query string? was reading this [doc](https://github.com/irods/irods_client_icommands/blob/b575fbd9627b1f1bd42c5012d3c8ba5582d78618/src/iquest.cpp#L53). 

Tried to add `uppercase` at the beginning of query_string, but seems like it's not working as expected. Any insights on this?

**Comment by trel** [comment]
Hmm, yes, that should be what we need... can you paste/link the query you're currently attempting?

**Comment by connectbo** [comment]
Sure, here's the query param I used - `irods-rest/1.0.0/query?query_string=uppercase+SELECT+order(RESC_NAME),RESC_TYPE_NAME,RESC_ZONE_NAME,RESC_VAULT_PATH,RESC_LOC,RESC_INFO,+RESC_FREE_SPACE,+RESC_COMMENT,RESC_STATUS,RESC_CONTEXT,RESC_PARENT,RESC_ID+WHERE+RESC_NAME+!%3D+%27bundleResc%27+AND+RESC_NAME+LIKE+%27%25TEST%25%27&query_limit=10&row_offset=0&query_type=general`. So yeah just in front of the query string, but looks like the result is the same.

**Comment by korydraughn** [comment]
If you're trying to execute a case-insensitive search via the rest API, that might require a new parameter. I believe the GenQuery API sets that via a flag and can't be part of the actual query string. I'll look into this and let you know what I find.

**Comment by trel** [comment]
correct - it's not part of the actual query string.

**Comment by trel** [comment]
related links...

https://github.com/irods/irods/blob/32cc2bd18e43aaaa42f002d07996343a05066646/lib/core/include/rodsGenQuery.h#L40

https://github.com/irods/irods/blob/7823236fcd9b2e1bfd40d9d74556259d4db9334b/server/api/src/rsGenQuery.cpp#L46

**Comment by trel** [comment]
@korydraughn this could be last thing in 0.1.0 if it's easy on the rest_cpp side of things...

**Comment by korydraughn** [comment]
it shouldn't be difficult to implement. i think this will require reverting to the GenQuery C API. i don't think the query iterator lib exposes the options for specifying case-insensitive search.

**Comment by trel** [comment]
sounds like a 0.9.0 and 0.2.0 thing to me.   bumping...

**Comment by trel** [comment]
rest_cpp issue... https://github.com/irods/irods_client_rest_cpp/issues/71

**Comment by trel** [comment]
looking at this again...

I think this is just a case-insensitive comparison/filtering within the values already stored in the serverContext in the browser...   No need to use the new /query parameter...   ?

**Comment by trel** [comment]
done!
