### ISSUE TITLE
resource filter should compare against both name AND hostname fields

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#69]
a booleon OR should be used...

so if the query matches either name OR hostname, it should appear in the result list.

**Comment by connectbo** [comment]
I investigated this a little bit today - the following query using `OR` won't work for some reason (0 matches) - `SELECT RESC_NAME,RESC_TYPE_NAME WHERE RESC_NAME LIKE '%${name}%' OR RESC_LOC LIKE '%${name}%'`. 

Interestingly, I found that`SELECT RESC_NAME,RESC_TYPE_NAME WHERE RESC_NAME LIKE '%${name}%' AND RESC_LOC LIKE '%${name}%'` did turned back the results that match both. So I guess maybe the `OR` operator is causing issue? Might need your genQuery brain here.

**Comment by trel** [comment]
OR has always been a tricky thing.    Try two separate queries and combine then uniquify the results...  We can optimize later...

**Comment by connectbo** [comment]
Got it. I can try and see how it looks like in this way. `limit` & `offset` might be tricky there.

**Comment by trel** [comment]
@d-w-moore you have the magic incantations...  can we do this in one?

**Comment by trel** [comment]
Upon further reflection... I think this has to be two queries...

the `||` syntax only applies when querying a single column for two different values... `COLL_NAME LIKE '%name%' || LIKE '%other%'`.

**Comment by trel** [comment]
due to the lack of GenQuery support for 'OR', the merged solution was to do two independent searches and uniquify the results.

Once GenQuery is smarter (https://github.com/irods/irods/issues/4069), this can be refactored here...
