### ISSUE TITLE
treeview not showing all the resources

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#76]
There are 18 resources in the catalog... but only... six(?) show up in the tree view?

<img width="789" alt="Screen Shot 2021-09-16 at 9 19 03 PM" src="https://user-images.githubusercontent.com/55238/133708515-2c7bb3b1-e0b4-4231-bf91-dc6c030c9ff6.png">

**Comment by connectbo** [comment]
hmm, that's unexpected. Didn't notice this when doing my work on the tableview, will take a look. Thanks for finding this bug!
