### ISSUE TITLE
Mismatch number of reported resources

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_zone_management_tool#77]
The number of resources reported by the side panel does not match the number in the table.

![Screenshot from 2021-09-17 09-18-27](https://user-images.githubusercontent.com/5543107/133789334-9d2c4ff2-849d-4914-afd4-1ab33c137b30.png)

From `ilsresc`:
```bash
compResc:compound
├── archiveResc:unixfilesystem
└── cacheResc:unixfilesystem
demoResc:unixfilesystem
ufs0:unixfilesystem
```

**Comment by trel** [comment]
this is because the compResc doesn't 'belong' to any server... it's pure virtual...?

**Comment by connectbo** [comment]
The resource number column in the server table would be the number of resources that have the same hostname as your server. I suspect one of your five resources might have some other hostname rather than `kdd-ws`?

**Comment by korydraughn** [comment]
I'll verify and post my findings.

**Comment by korydraughn** [comment]
The numbers make sense upon the explanation, but are people expected to know this? Is this even a bug?

**Comment by trel** [comment]
I think it's correct... and that we can add a little explanation perhaps... to the servers page...    but not exactly what it should say.

but more generically, we can introduce a 'sanity check' facility that can run in the background and populate the front page... created #79 for this.

we could also put a 'warning' color or something on the resources list where a hostname doesn't match a known server hostname.... created #80 for this.

**Comment by trel** [comment]
I think we close this for now - there is no bug, and as the status/home page gets smarter, I think things will become more self-explanatory.
