### ISSUE TITLE
add annotation/color to resources that have hostname that doesn't match a known server

### ISSUE THREAD

**Issue by trel** [irods/irods_client_zone_management_tool#80]
on the resources page...

this would not be defining these values/entries as 'errors'... but rather just alerting, visually, to the administrator that they have a value set that is not currently 'housed' at a known server (as defined by the zone_report).

for example:
- two servers in the Zone, with hostnames 'a' and 'b'...
- a resource that has a hostname of something other than 'a', 'b', or 'EMPTY_RESC_HOST' should get this visual distinction in the listing.

**Comment by trel** [comment]
this can also be incorporated as a 'check' as part of #79

**Comment by connectbo** [comment]
I think we can close this - pr got merged back in December

**Comment by trel** [comment]
indeed.  thanks.
